### ISSUE TITLE
HW1 fighter and corvette tech trees

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#30]
**Fighter tech**

Currently, the only purpose of the fighter drive is to unlock the fighter chassis, with no new units becoming available once the first research is complete. The proposal would be to integrate the fighter drive and chassis researches into the same research so that this takes as much time and as much RUs as the sum of them both.

Alternatively, the fighter drive could unlock ints production and researches for bombers, defenders, etc. In this case, times and costs might require some adjustments, but it would allow a faster unlock of ints if bombers are not needed in the early stages of the game.

**Corvette tech**

In this case, the problem is unlocking salvettes before being able to produce more advanced corvettes, for example multiguns, which are anti-fighter while salvettes are not. The proposal here is to have heavy corvette upgrade, fast traking turrets, minelaying tech and salvette tech all unlocked after the corvette drive research. If one is being swarmed hard by fighters, s/he doesn't need salvage corvettes but multiguns instead.

**Comment by Novaras** [comment]
#### Fighters:
[This would be a *nerf* to HW1 fighters if you were simply to add the cost/times together.](https://drive.google.com/open?id=1rF7E8XZdkqsnKQRWpBAzNtBQ6T7VEfIF)

As you can see, if you were wanting to tech both standard fighters and defenders, you would essentially have to be researching the old Fighter Drive tech *twice*... so this change isn't as simple as that.

#### Corvettes:
Same problem as above, not a straight-cut change. Corvettes would be hit even worse simple due to a higher branch count.

#### Options:
* Add base to branches (big nerf)
* Add `base / branch_count` to branches (small buff, can develop into big buff if `branch_count` is high)

In both cases the second approach is probably appropriate... In comparison to HW2, HW1 'advanced' vettes come out laughable slowly. HW2 merely needs to construct a vette facility to reach this tier of corvette, Hiigaran especially get both of their combat corvettes immediately.

**Comment by cloaked2222** [comment]
Tech trees are basically fixed cannon. Yes even the fighter drive/fighter chassis thing, lol. I believe tech tree's match the classics other than:
hw1 no longer has bomber research (I'm open to bringing this back, as it was removed for poor reasons imho, someone was afraid of hyper-torps...)
hw1 carriers and destroyers have been swapped (to balance vs hw2)
hw2 no longer has lv2 upgrades (to balance vs hw1)

hw1 research times/costs are on the table for changes. Corvette chassis (salvage corvs) can come down if needed. Years ago it was set high for fears of salvage corvs, however counters to salvage corvs have also been improved since. Years ago there was a time when salvage corvs + GWs made vaygr cry. However HMF now have an anti-corvette missile, vay ass frigs aren't useless vs corvs anymore, etc. Salvage corvs were scary for hiig too, but that's why there's torps.

**Comment by cloaked2222** [comment]
See here for hw1 research time buffs: 
https://github.com/HW-PlayersPatch/2.3/issues/53
