### ISSUE TITLE
Missile Destroyers

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#39]
Fear asked me about MDs, so I checked for potential improvements.

hw1c DD: http://well-of-souls.com/homeworld/kushan/destroyer.htm
hw1c MD: http://well-of-souls.com/homeworld/kushan/missile_destroyer.htm

Potential changes to MD, to align better with hw1c:
Cost: 2000->2750
Health: 65k->101k
regentime: 1850->1164ish (no idea where gearbox got some of these regen numbers from, i assume there was a method to the madness here)
Potential tweaks to weapon penetration if needed.

**Comment by Novaras** [comment]
knock 20s off the build time
101k sounds okay although i wouldn't have put it that high, price makes me uneasy, thats extremely high

missile barrage ability should probably have some other additional effect instead of 'lots of missiles'... currently (afaik?) its an always-use-whenever ability with no decision making involved

**Comment by cloaked2222** [comment]
Build time aligns with classic, so don't change that.
Set health to 101k then (55% buff)
Cost to 2750 is a 38% nerf, seems fine considering you getting a much more durable ship.

Research time or cost can be adjusted as you feel fit. Feel free to tweak ability.

**Comment by Novaras** [comment]
don't enjoy aligning with classic as a philosophy, not only because my personal belief is that no game developed by relic has ever been competitively balanced, but also because this is *not* classic, not the mechanics or anything, and especially because from HW1's perspective we have two new additional races to contend with...

im fine using classic stats as a base to work off

HP: `65000 => 101000 (+55%)`
Build time: `160 => 140 (-13%)`
Cost: `2000 => 2750 (+38%)`
Res cost: `1400 => 1600 (+14%)`

thoughts?

**Comment by cloaked2222** [comment]
Just keep it simple and go with the bigger changes. That 13% buff and 14% nerf feel like more noise in an already over-cooked update.

Compared to the standard attack, what about making missile barrage better against a certain ship class and worse against another?

**Comment by Novaras** [comment]
my thoughts exactly, although im not sure how to swing it, i was considering even making it a long cooldown burst vs medium armour or something

**Comment by cloaked2222** [comment]
#### Missile Destroyers
- Cost 2000->2500 +25%
- Build Time 160->145sec -9%
- Health 65k->101k +55%
- Now count againt the destroyer unit cap like hw1c. Normal unit caps allow for six destroyers, two of which can be missile destroyers.
