### ISSUE TITLE
HW1 Ship Design for Build Costs/Times

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#51]
The basic ship properties are build costs, times, ship speed, and health. Getting these right requires a good top-down design. Generally these should have a similar feel to the classic games, while being balanced for HWR.

Many kus/tai build times in 2.0 were a hodge podge of times, with no real design. I've been wanting to implement a proper design for a while, but so far things have only been improved as needed. Fighters/Corvs/Frigs all need work. The other ship classes already look good between b7 and current plans for b8 (like cc build time).

Today I finally took a crack at creating a proper build time design, the results are below.

Current hw1 build time factors: (a factor of hw2 build times):
Fighters: 1x for ints, other fighters are random numbers...
Corvs: 1.33x with a pretty good design as of b7
Frigs: 1.5x, slow as fuck

After much thinking, i settled on a factor of 1.25x for hw1 fighters/corvs/frigs compared to hw2. I then set hw1 ints, heavies, and ions to 1.25x their hw2 counterparts (so 9sec, 19sec, and 55sec). I then looked at the hw1c stats to determine where the other fighters/corvs/frigs should initially fall. I then made some tweaks, as some ships may need to build faster or slower than their hw1c design. I'm still not sure about some ship build times, so I left question marks. All work so far is just in this excel file for discussion.

**Edit:** Updated to 1.25x for Fighters, and 1.33x for Corvs/Frigs

**Build Times**
Ship Name | b7 Times | Ideal Times (green) | hw1c Times (purple)
![image](https://user-images.githubusercontent.com/18016573/41829389-79aedc68-7808-11e8-8053-c7398e215373.png)
![image](https://user-images.githubusercontent.com/18016573/41829437-b7b5d64c-7808-11e8-956d-429200e54bd1.png)
![image](https://user-images.githubusercontent.com/18016573/41829455-ddb25384-7808-11e8-985c-6e57787e6e87.png)
![image](https://user-images.githubusercontent.com/18016573/41829472-ef1b2f06-7808-11e8-80e1-7a2ad170024b.png)
![image](https://user-images.githubusercontent.com/18016573/41817055-820222b4-7761-11e8-9012-91639418169d.png)

**Class Ratios:**
![image](https://user-images.githubusercontent.com/18016573/41806469-93b04dd6-768c-11e8-8395-0c96ae3845d7.png)

Keep in mind we can change hw1 research times too as needed.

HW1 Ideal Design.xlsx spreadsheet is here:
https://github.com/HW-PlayersPatch/2.3/tree/Cloaked/Balance%20Info

**Comment by Novaras** [comment]
pretty huge changes, don't think we should even attempt this for v8

why fighters being 1.25x?

**Comment by cloaked2222** [comment]
Frig changes are big (but needed). Corvs are mostly barely budging, slower minelayers (25->30), repair corvs could stay at 20 if you wanted.

Wanted fighters/corvs/frigs to be consistent around 1.25x.
first research ship: 50->45 (to match hubs)
resource collectors: 50->45
This will free up build ques early on to allow ints to go from 7sec to 9sec. Scouts building slower than ints was hella silly, they can come down from 10sec to 8sec. Research time for fighter drive/chassis can come down as/if needed.

**Comment by cloaked2222** [comment]
Build costs are already overall good, however I did a similar design review on them just to be sure. Only came up with 2 changes.

1. Bombers 120->130ru. This better aligns with hw1c, and hiig/vay bomber costs.
2. Gravity Wells can go from 800 to 1000. To match hw1c ratio to ion frigs would be 1100ru, however 1k works better vs hw2 races. I actually wanted to do this years ago, but gearbox didn't change it for whatever reason.
hw1 path: 600res,800cap drive,500gwtech,1000gw = 2900ru
hiig path: 1500res,1000inhib = 2500ru

See:
Cloaked\2.3\Balance Info\HW1 Ship Design.xlsx

**Comment by Novaras** [comment]
is this really something you want to bundle with v8? The changes for hw1 are already voluminous and extensive and in many cases, quite fundamental.

It also seems like you're pretty much disregarding any content in the props which is already down... defenders already have a HP buff for example, minelayers already had their side/back armour removed. If you're instead basing all of this with that stuff in mind, fine.

I'm all for overhauling HW1, but I'm also sure you don't need me to tell you that many small, sensible changes will amplify eachother into probable chaos... aside from testing the already-implemented changes, I was fairly happy with the state of v8 and didn't want to make any further changes. I'm also surpised at how ready you are to overhaul the entire cast for HW1 but are afraid the vaygr imp. upgrade cost would be too much for a single release, and other alsmot trivial changes such as two extra movespeed on motherships... the only mission where the MS needs to move at all is the one where it moves in range of some relic, and its speed is manually set in that mission.

At this point I'm really not sure what your direction is for this update at all, nor am I sure that any of the work so far is being taken into account with this overhaul. You realise most of the testing that's been done has been done with equal RU/time costs and will potentially have to be redone after this? Add in the rest of the units which will also probably need testing...

Where did you get this 1.25x number from? Are you basing this off the games we played on live 2.3? Why? None of this should be based on a previous update since we have so many changes already.

Why did you rebuff HW2 scouts? Your perception that they are somehow worse than hw1 scouts is confusing at best honestly, the main abuse of scouts is a circle waypoint (so it repeats), not running away and then coming back. 

Vaygr scouts are sitting pretty with 588 movespeed after upgrade, yet you're fine with rebuffing them? Last time you blew this off saying it was trivial to intercept them, but its really not at all. You can also just dip out and dock them for free, whereas a hw1 scout is a lost 70ru every single snipe. By no means am I saying your ideas are *wrong*, but I sincerely wish you'd make an issue or at least ask opinions before changing, up until now my perception of this whole project was that we weren't going to veto or overwrite eachother's work and that's why we were using version control in the first place... You surely already know I think scouts are a stupid unit concept to begin with and the only reason I didn't hit their speed was because you didn't seem happy with it.

**Comment by cloaked2222** [comment]
That's a lot for one post. =) Breaking replies into 3 sections:

**General**
See here first: https://github.com/HW-PlayersPatch/2.3/issues/54

**HW2**
See here next: https://github.com/HW-PlayersPatch/2.3/issues/50#issuecomment-399807932

**HW1**
With hw1, I truly feel we can't continue duck taping the race as we've done since HWR was launched. Gearbox mol just put the race in the game, without developing a good balance design. hw1 needs a top-down design review. I'm not saying change everything, but this review will help us see 'what hw1 prolly should have been', and then we can pick our battles and change whats really needed, while keeping some stuff that maybe isn't ideal.

As part of this review, yes I did consider the props like the defenders and minelayers. I reviewed all the Kus/Tai .research and .ship changes yesterday before making this thread. I will be making a Kus/Tai Review post about them later today, similar to the Hig/Vay Review post i made two days ago. You guys have really lead me to believe that hw1 needs an overhaul. So it may take more time and testing if we want to go down this path. 

As far as direction for 2.3, we need to decide on whether we're going to really overhaul hw1, or just continue to band aid it. Let me know, your thoughts. Not like I had any intentions of over-hauling hw1 on my own prior to your involvement. I'm not too concerned about a build 8 vs build 9 at this point, need to get our heading first. Build 8 will likely be carved out of the bleeding edge with the stuff were really confident on, while we continue to test the rest for build 9. I don't have any timetables.

In summary, for the HW1 Ship Design:
**Build Times:** Just tinkering with an 'ideal state'. Had I been the gearbox dev, this is prolly where i would have started in 2015. Yesterday 1.25x seemed about right, and that's where the spreadsheet landed. Thinking more today, corvs are prolly fine in b7 at 1.33x, and we could just drop frigs to 1.33x which is basically what we had been discussing already. This would be a much smaller change for corvs/frigs. Regarding fighters, they just look dumb atm with scouts building slower than ints. Adding 2sec to ints, and removing 2sec from scouts seems like a logical first step - that puts them at 1.25x.
**Build Costs:** 2 minor changes for b8 if they're cool.
**Speeds:** Already a WIP, not covered in this thread.
**Health:** Only a few changes that haven't already been proposed/discussed, seems b8 if they're cool.

**Comment by cloaked2222** [comment]
Fear: "13s for cloaked fighters is fine, 15s to build a fighter feels god awful and has a pretty similar effect on the unit that the 40s build time had on hs gates: you can never dedicate the time. Consider that you realistically need 15 or more for the time investment to potentially pay off. Not a fan at all. I would prefer to have strong specialists and then go from there as the races need flavour."
I'm ok with 13seconds. hw1c build time is obviously lol here. I'm sure it wasn't a great move in multi back in the day... I think I heard most of the 4 race specific units were kinda UP. We really could use a hw1c guy on the team again...

Cloaked: "Drone Frigate: b7 build time=77, Fear=45, Cloaked 77. Build time review puts this at 75sec if we were to buff all hw1 frig build times."
Fear: "Drone frigates I didn't touch in ages but again, I am never spending 75 seconds building a unit which is intended to be my races counter to fighters... This unit would lose in a production war with interceptors no doubt. Not to mention the fact that you would never be able to react effectively to fighters with a 75s slow unit... If you really want this, this unit would need to outperform vaygr assault frigates, which it isn't even remotely close to doing right now."
Best to worst vs fighters should be: Drones->Flak->Vay Assault Frigs. Someone would need to run tests, as I haven't in a long time.
Flak sit at 50sec, vay ass at 45sec. I'd prolly still be building 2 flak frigs if they were 100sec, they're that useful. hw1 specialist frigs can go as low as hw1 assaults if necessary (60 in spreadsheet), not lower.

**Comment by cloaked2222** [comment]
Implemented:
https://github.com/HW-PlayersPatch/2.3/commit/17f85486f4ba1a626f39be97aadd42eb2c2974f7

Made a few tweaks from the OP, based on testing and discussion.
