### ISSUE TITLE
HW1 Race Design for Research Costs/Times

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#53]
After doing the ship stat review I reviewed hw1 research costs/times, and imho they suck. This is an area that we paid little attention to in the past, other than requesting a few time tweaks really.

It looks like scole significantly changed them between v1.0 and v2.0 - but i have no idea what ryme or reason he used. Thankfully he seems to have improved them over the complete pile of shit that they were in v1.0. FYI scole took over balance design a month or two after HWR's release. At release hw1 ships were just 'in the game' really, often copies of un-upgraded hw2 ships. HWR balance stayed mostly the same from v1.0 until v2.0 other than some bug fixes.

The below ideas are just are a potential 'ideal state'. Dunno what your guy's thoughts are this. We could try to massively change all research cost/times, go half way between ideal and current, just band-aid the worst offenders, or stick with what we got...

Times listed below are the time it takes to start building a ship, assuming game starts at 0sec and RU isn't a problem. This includes faster times when Hiig has to get an adv module.

**Tech Tree Times:**
b7 Time (1   res) | b7 Time (1->2 res) | b7 Time (1->2->3 res) |
Path |
Ideal Time (1 res) | Ideal Time (1->2 res) | Ideal Time (1->2->3 res)
![image](https://user-images.githubusercontent.com/18016573/41824520-7f110c68-77df-11e8-82c6-d1b73df3c3e2.png)
![image](https://user-images.githubusercontent.com/18016573/41824523-881c4c82-77df-11e8-9c37-70fe1683c976.png)
![image](https://user-images.githubusercontent.com/18016573/41824528-95a55df8-77df-11e8-8e09-b25001a63f77.png)
![image](https://user-images.githubusercontent.com/18016573/41824531-9db03c98-77df-11e8-80a8-9f8f672766b1.png)

Its quite possible this is an over-buff on research times, but remember research cost is another limiting factor at our disposal. After coming up with the approximate tech tree times above, I then set individual research times in the spreadsheet to match:

**Research Times**
b7 Cost | b7 Base Time | 1x res | 2x res | 3x res |
Ideal Cost | Ideal Base Time | 1x res | 2x res | 3x res |
hw1c Time 1x res (no base time) | 2x res (assume twice as fast) | 3x res | 4x res
![image](https://user-images.githubusercontent.com/18016573/41824540-b30aba32-77df-11e8-8d9a-83e8e2ce82b3.png)

I believe tech tree's match the classics other than:
1. hw1 no longer has bomber research (gbx removed it to allow hw1 players to counter hyper-torps easier, since it takes longer for hw1 races to get GWs than hw2 races to get Inhibitors.)
2. hw1 carriers and destroyers have been swapped (to balance vs hw2)
3. hw1 can now build refineries at the start of the game (used to require capital ship drive. I'd like to bring this back to nerf hw1 hyper-caps. Since hw1 has no mods, its very hard for hw2 to counter these when they don't know if hw1 is building fighters, or corvs, or frigs)
4. hw2 no longer has lv2 upgrades (to balance vs hw1)

Balance Design.xlsx spreadsheet is here:
https://github.com/HW-PlayersPatch/2.3/tree/Cloaked/BalanceInfo

**Comment by cloaked2222** [comment]
@Echo1707 - I'm updating SP research too, it hadn't been touched since HWR v1.0....

Can you think of any problems this might cause? For example I want to make sure the player has enough RU in mission 1, to afford the more expensive upgrades.

**Comment by Echo1707** [comment]
I was missing `-moviepath DataHW1Campaign`, so the correct path for me is:
`"D:\Program Files (x86)\Steam\steamapps\common\Homeworld\HomeworldRM\Bin\Release\HomeworldRM.exe" -moddatapath 2.3\2.3_Update -overridebigfile -dlccampaign HW1Campaign.big -campaign HomeworldClassic -moviepath DataHW1Campaign`

That said:

HW1C M01 end: 7 scouts, 1 salvette, 1 coll, 1 research ship and 430 RUs
HW1RM M01 end: 7 scouts, 1 salvette, 2 colls, 1 research ship and 600 RUs 

HW1C M02 end: 7 scouts, 3 repair vettes, 8 salvettes, 2 colls, 1 research ship and 191 RUs (seems like you actually need a combat corvette of some sort, otherwise this missions takes very long)
HW1RM M02 end: 7 scouts, 3 repair vettes, 14 salvettes, 2 colls, 1 research ship and 19 RUs

HW1C M03 end: 
HW1RM M03 end: 2 enemy assault frigs that gave 559 RUs, 7 scouts, 3 repair vettes, 14 salvettes, 2 colls, 1 research ship and 5951 RUs

HW1C costs: (scout: 35; int: 55; repair vette: 150; salvette: 220; light vette: 135; heavy vette: 240; support frig: ; assault frig: ; collector: 650; controller: ; research ship: 700)
HW1RM costs: (scout: 70; int: 100; repair vette: 175; salvette: 250; light vette: 225; heavy vette: 250; support frig: 600; assault frig: 700; collector: 500; controller: 900; research ship: 600)

Notes:
HW1C: corvette drive can be researched in M01. Research times for HW1C are really long (corvette chassis and heavy corvette upgrade took around 2 mins and 40 seconds each; total of 5 mins and 20 seconds; these were the only two researches in M02); It took aroud 17 minutes to harvest all the resources on M02 (this counting the second resource collector I made too)
HW1RM: corvette drive is unlocked in M02. It took 11 mins and 50 seconds into M02 to have enough RUs to research everything without building anything. The event when the Turanic Carrier launches two wings of enemy crafts after the salvage corvette is back with the audio recording came earlier than intended and the two pings in the sensor manager where in an obviously wrong position; when the enemy ships actually spawned, the pings correctly tracked them. M02 took 40 mins and 16 seconds.

The very first missions are doable, but they take a long time to complete. Campaign is unbalanced and people think that defenders/multiguns are the answer to swarmers (at least multiguns should be), but in practice they are not; this leads to a waste of RUs in M07 and M08 that depletes your bank (I have to think at what new players would do).

**Comment by Echo1707** [comment]
https://github.com/HW-PlayersPatch/2.3/pull/106

I hope it's okay :)

**Comment by cloaked2222** [comment]
Cool that was fast. :) Looks like you updated quite a few missions, does this statement sum it up?
"Adjusted campaign resources, for the research cost changes described in the balance section."

Also doing a M1 run-through right now, and I noticed there's no Fighter Drive research. Did GBX remove it at some point? Maybe its time to combine Fighter Drive and Chassis into one research item...
