### ISSUE TITLE
Kus/Tai Review

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#56]
I reviewed all Kus/Tai .ship file changes on github for the first time yesterday, and made the following tweaks in my local cloaked branch. I haven't committed anything to github yet, as some changes prompted me to do a full review on HW1 Ship Build Cost/Build Time/Speed/Health (see the other threads).

**Ships:**
- Restored the default stance/ROE design to all ships other than colls and swarm (so AI don't suck). Since there's no negative that can be applied to colls/probes/etc when in evasive, I propose we remove the stance based speed buffs on these ships.
- Repair corv, restored 1% healing stance nerf when in evasive. Evasive stance is meant to boost power to thrusters while reducing power to guns/heal beams. Stances are meant to give players choices, when one stance is 100% always the best, that's not good.
- Assault Frig sideArmourDamage/rearArmourDamage back to 1.2. All frig sideArmourDamage stays at 1.2 per Relic's design. hw2c had this, and I believe hw1c had this too. "sideArmourDamage actually covers ~98% of the ship. rearArmourDamage covers a ~1% cone in the direct rear, and there's a ~1% cone in the direct front that receives normal damage"
- Assault Frig rotation speed tweaked to be consistent with other similar frigs.
- Cloaked fighters speed. b7: Thruster=331 Engine=430. Fear: both 420. Cloaked: both 430
- Cloaked fighters can now stay cloaked indefinitely per hw1c, as me/fear have discussed before. Also included the bug fix to prevent them from cloaking nearby ships.
- Cloak Generator effective health b7: 7200, Fear: 11k, Cloaked: 9k. This aligns with the hw1 Ship Health review I did.
- Cloak Generator speed b7: 165, Fear: 230, Cloaked: 206. I set this to match assault frigs per hw1c in May. Looks like you over-wrote these changes when you merged the Fear branch over the Cloaked branch on June 2nd.
- Drone frigate speed b7: 166, Fear: 230, Cloaked: 206. Same as above.
- Light corvette health: b7: 900, Fear: 800, Cloaked: 900. This aligns with the hw1 Ship Health review I did. Weapon should be nerfed here, not health.
- Removed resource controller build time buff. There's also backstory here around the hypercap strat, so I'm very hesitant to buff this. Also seems fine as is:
hw2 coll: 30sec, ref: 45sec
hw1 coll: 45sec, ref: 60sec
- Further buffed Tai Field Frigate rotation speed/accel/brake to match hiig DFF.

Fear and myself had some slightly different speeds for some corvs, so I'm going to do a hw1 speed review later.

I'll review weapons later.

**Comment by Novaras** [comment]
If you are going to revert the evasive ships, then just make it so colls don't get a bonus in any stance either? Confusing.

Repair corvs, fine.

Assault frig side armour was supposed to be reversed to 1.2, I think it actually might be in the branch.

Cloaked fighters got clunked on speed to discourage careless use of the unit and to allow them to be chased down by ints more easily as a punish... they'll naturally spend more time in radius of slower ships too. Keep mine I'd say.

Cloak gen, not too much fuss here... HW2 cloak is just SO much more survivable in most scenarios I thought anything less than 10k on this unit was frustrating to use. I'm fine with either speed... for my preference I prefer snappy units which can react fast, especially utility.

Drone frigate speed went way up due to their target unit class, can be the same as other frigates for whatever reason though...

Assault frigate rotation can't be the same as it was in classic because we are dealing with hw2 corvettes which are circling their target with no micro involvement, perhaps in classic a skilled player could have manually simulated this and in that situation a slow rotater is fine as its a reward, in this scenario its one of the only solutions I have to make assaults decent against circlers without being laughably good against strafers and runby users (lasers). Also note I have another branch running related to this unit (again), they aren't finished imo

**Comment by cloaked2222** [comment]
Ya I was suggesting we remove stance bonuses for colls/probes/utility type ships where aggressive has no value. I just checked hw1c and it doesn't appear to have this non-sense. Probes and collectors move/turn the same there regardless of stance. @Echo1707 - Perhaps you'd like to do tackle this removal? :)

For cloaked fighters, I checked the file history, looks like this is what happened:
b7:
NewShipType.thrusterMaxSpeed=430*0.77
NewShipType.mainEngineMaxSpeed=430
Cloaked:430/430
Fear:440/440
Fear Again:420/420
420/420 actually results in slightly faster top speed over b7. You'd think otherwise just reading the property names, but in game tests have revealed these two combine somehow to affect top speed. We should prolly just stick to b7 here, since its hardly a noticeable difference.

Thanks for assault frig rotation explanation, that makes total sense. Hiig torps don't have this issue, as they have torps... This change is fine then, they're still slower than support frigates.

**Comment by Echo1707** [comment]
Stances for collectors had another role: in aggressive they kept mining even if under fire, in evasive they stopped mining and docked with the closest ship for repairs.

Sure, I can do that :) Just to confirm, I branch out of `Cloaked` (because you already have restored the default stances) then set all multipliers to 1.0, even for collectors. Right?

**Comment by cloaked2222** [comment]
Ya in hw1c, stances and ROE were combined. GBX actually did that in developing 2.0, but rofl the only way to use evasive was in passive... I suggested we change it to 4 buttons:
- Aggressive = Agg ROE/Agg Stance
- Defensive = Neu/Def
- Evasive = Eva/Def
- Passive = Eva/Pas
But we ended up with 6 buttons -_-

Echo, you can branch these changes out of Cloaked. We'll merge your stance branch into the bleeding edge later (the main branch).

We can change a lotta hw1 stats and thats fine, but the 4 main .ship stats that people see/feel in game need to reflect hw1c (Speed, Health, Build Cost, Build Time). Now that I'm done with that HW1 Design Spreadsheet, here's the rest of my Kus/Tai .ship tweaks:
- Defenders: b7 Health=360 sideArmourDamage=0.9, Fear Health=400 sA=0.9, Cloaked Health=400 sA=1.0 to line up with the hw1 health review.
I did some tests and in hw1c, this ship looses to interceptors in equal numbers. So if you maxed 70 fighters, you wanted 0 defenders. Their main advantage appears to have been build speed - which was half that of an interceptor. So you could spam these to hold a defense. Compare that to HWR v1.0 where the defender was the best hw1 fighter, so you would get 70 of them and walk around the map with a ball of mini-flak frigates... Hence they were given a unit cap in v2.0. Propose we re-think this unit some.
- Cloaked Fighters: b7 build time=15, Fear=13, Cloaked=15. Like to leave this alone atm, ship is already getting huge buffs.
- Light Corvettes: b7 speed=285, Cloaked May 295, Fear 320, Cloaked June 305 per hw1 speed review. I like these being faster than vay corvs now. =)
- Multi Corvettes: b7 speed=275, Cloaked May 305, Cloaked June 320 per hw1 speed review.
- Multi Corvettes: b7 health=1100, Fear 900, Cloaked 1100. Per health review, health should go up to 1400 if anything. This ship isn't meant to be cannon fodder.
- Minelayer Corvette: b7 speed=246, Fear: 270, Cloaked 255 per speed review.
- Drone Frigate: b7 build time=77, Fear=45, Cloaked 77. Build time review puts this at 75sec if we were to buff all hw1 frig build times.

All these changes are now in the Cloaked branch.

**Comment by Novaras** [comment]
Let's change defenders to act like hw1c

13s for cloaked fighters is fine, 15s to build a fighter feels god awful and has a pretty similar effect on the unit that the 40s build time had on hs gates: you can never dedicate the time. Consider that you realistically need 15 or more for the time investment to potentially pay off. Not a fan at all. I would prefer to have strong specialists and then go from there as the races need flavour.

Light vettes at 320 is nice and makes sense.

Don't know if multis also need the speed, light vettes are losing their identity...

Iirc multigun HP change was very intentional and due to them overperforming in matchups as well as taking far too long to bring down... 1000 HP might be nice but 1400 is insanely high.

Fairly ambivalent about minelayer change, 270 was more like a QOL change.

Drone frigates I didn't touch in ages but again, I am **never** spending 75 seconds building a unit which is intended to be my races counter to fighters... This unit would lose in a production war with interceptors no doubt. Not to mention the fact that you would never be able to react effectively to fighters with a 75s slow unit... If you really want this, this unit would need to outperform vaygr assault frigates, which it isn't even remotely close to doing right now.

**Comment by Echo1707** [comment]
Please have a look at [Cloaked...Utility-stance-multipliers](https://github.com/HW-PlayersPatch/2.3/compare/Cloaked...Utility-stance-multipliers) comparison:
- in many files I found `NewShipType.sideArmourDamage = getShipNum(NewShipType, "sideArmourDamage", 1.0)` instead of `NewShipType.sideArmourDamage=1` (the latter is more readable)
- GWs side and rear armour damage values are 1.2 (a value of 1.2 means that the damage is multiplied by 1.2? If yes, why not in the rear too? If instead the damage is divided by that value, then why the front is weaker than the sides?)
- Resource Controllers have `sideArmourDamage=0.9` but `rearArmourDamage=1`
- Kushan Resource Controllers have `NewShipType.paradeData="kus_repairer_parade"` while Taiidan Resource Controllers have `NewShipType.paradeData="dummy_parade"` (this is more of a reminder for myself to check how this translates)

**Comment by cloaked2222** [comment]
getShipNum(NewShipType, "...", 1.0) lines check the props. This allows different values to be used in MP, SP, gamemodes, etc. Generally leave things as is, unless we actually need to change a value. More info:
https://forums.gearboxsoftware.com/t/latest-update-killed-my-mod/534468/6

1.2 = ships take 1.2x damage on the side, as discussed elsewhere if you search the issues.
sideArmourDamage and rearArmourDamage are covered in the HW1 health review:
https://github.com/HW-PlayersPatch/2.3/issues/55

Plz check and fix parades formations for those 2 ships if needed. FYI, NoOne improved the Kushan parade formation file in 2.3 back in b5 or b6.

**Comment by cloaked2222** [comment]
Echo, your stance changes look good. Just remove the armourdamage comments/changes, and change all collector default stance to neutral. Then its pull ready.

**Comment by Novaras** [comment]
Let's do that for v8, will try to have something up by tonight

Keeping track of which version changes are now intended for is a hassle yeesh

**Comment by cloaked2222** [comment]
Echo, that's basically correct. See the HW1 Design for Health thread, which would have it changed to 1x all around.

> Fear: "could we not simply remove these lines? Afaik the values are 1.0 unless specified"

Lets stick to changing things that have an impact on players. If we start cleaning up the code, we'll sink a lot of time into something that has zero affect on players. This will also make it much harder for modders to merge the 2.3 changes into their mods. Its also possible such changes will have unintended affects that were not aware of. Trebic for example has largely re-written/cleaned up many scripts and files in HWR, but the changes are massive, and I did not want to introduce that in 2.3.

**Comment by cloaked2222** [comment]
Fear, I missed a minor change in the OP:
hw1 scouts secSensorRange, b7=11000, Fear=8030, Cloaked=8000
Just rounded out the number when I was tweaking hw1/hw2 scout ranges. This is less than a 1% change so didn't even bother to mention it.

Also, I've been thinking on this this week:
Cloaked fighters regentime, b7=0, Fear=240
While I liked this idea the first time I heard it, no other fighters/corvettes have ever been able to regenerate health by design - and must be docked to heal. This should not go in 2.3.

**Comment by Novaras** [comment]
do whatever

**Comment by cloaked2222** [comment]
Made some updates per Fear/Echo from our discussions above:
Cloaked Fighter build time = 13sec
Took a first stab at updating defenders to act like hw1c by buffing build time from b7's 9sec to 7sec.
I corrected the tai_resourcecontroller.ship to "tai_repairer_parade" to match kushan.
https://github.com/HW-PlayersPatch/2.3/commit/4827ebb378aebb4f7e4ef424ceda7093d889f8f0
