### ISSUE TITLE
Stances might have bad multipliers for some ships

### ISSUE THREAD

**Issue by Echo1707** [HW-PlayersPatch/2.3#6]
Following is an example of stance multiplier found on the Taiidan Interceptor .ship file. The three numbers are the multipliers for evasive, aggressive and neutral stances respectively:

`setTacticsMults(NewShipType, "DAMAGEAPPLIED", 1.10, 0.90, 1.0)`

Certain ships might have some multipliers wrong. The following is taken from the 2.1 (vanilla) version of the Taiidan Interceptor .ship file:

`setTacticsMults(NewShipType, "MAXSPEED", 1.0, 1.10, 1.0)`
`setTacticsMults(NewShipType, "WEAPONDAMAGE", 1.20, 1.0, 1.0)`
`setTacticsMults(NewShipType, "BULLETSPEED", 1.15, 1.0, 1.0)`
`setTacticsMults(NewShipType, "DAMAGEAPPLIED", 1.10, 0.90, 1.0)`
`setTacticsMults(NewShipType, "FIRERATE", 1.0, 1.25, 1.0)`

This means that the Taiidan interceptor is 10% faster and deals 10% less applied damage while in aggressive, has a 20% increase in weapon damage, 15% increase in bullet speed and 10% more applied damage while in evasive, compared to a neutral stance.

The only way to check if these multipliers are fine would be to check every single .ship file. At the same time, modifying these multipliers means that ships (expecially strikecrafts) needs to be rebalanced.

**Comment by Novaras** [comment]
https://forums.gearboxsoftware.com/t/hwr-2-0-modding-changes/1501768

Format is Aggressive/Evasive/Neutral.

The numbers seem correct to me already? In Discord you tell me:
![log](https://user-images.githubusercontent.com/17747768/40843613-7b17e12e-65a9-11e8-8daf-4fe223e62c83.png))
Which *does* seem to imply the opposite, however I suspect this is related to `FIRERATE` rather than the function `setTacticsMults`

**Comment by Echo1707** [comment]
`FIRERATE` is confirmed to be a divider rather than a multiplier. I opened this issue on the assumption that the format was Evasive/Aggressive/Neutral based only on the `FIRERATE` "multiplier". This issue doesn't really exist, so I'm closing it.
