### ISSUE TITLE
repo organization

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#60]
in light of the work going on which afaik is meant for v9 (such as https://github.com/HW-PlayersPatch/2.3/issues/51), the repo probably needs some organisation which i can fix up if nobody minds, some stuff may need to be shuffled about...

**Comment by cloaked2222** [comment]
Sure, have at it.

**Comment by cloaked2222** [comment]
There's been some talk of b8 vs b9. So I added a b8 milestone to most of the issues that weren't already marked b9.

I set the potential HW1 Research changes to b9.

We need to decide on a milestone for the HW1 Build Costs/Times/Speed/Health changes. If were going to do most of these and really overhaul HW1, i feel these changes should go into build 8. Otherwise we don't have to do any of these changes, and can just keep those threads as sort of a guidestone for when future changes are needed.

**Comment by cloaked2222** [comment]
Just pulled the wip or b9 stuff out of bleeding edge, and into their own branches:
HW1-Research (build 9 imho)
Unit-Caps (needs to be discussed, make an issue. Also these need to be applied to other folder locations, unit caps are all over the place in HWR...)
Ship-Multipliers (wip)
Hiig-Torps (i need to test later, maybe b9)

**Comment by Novaras** [comment]
cant do anything while `Cloaked` is still trying to be pulled into `bleeding-edge`, no idea why this is happening

other branches need to be finished and cleared up before we can apply any organization

**Comment by cloaked2222** [comment]
Cleaned up some branches:
hw1-assaults: Had no differences from bleeding edge, so deleted the branch.
HW1-research: Only had two changes, so posted them into the HW1 Research thread, and deleted the branch.
Ship-Multipliers: Had a couple early TO changes, prior to the TO-hack branch. The other changes are in the 'Tai Defense Fields and Field Frigates' thread.

**Comment by cloaked2222** [comment]
I re-organized the file structure better, then merged Bleeding Edge into Master. Then basically renamed Bleeding Edge to "WIP" for build 9.
