### ISSUE TITLE
SP vs MP stats

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/2.3#62]
Some stats are different in SP than MP. This is done like so:
ship\hgn_mothership\singleplayer\props\default.lua
Number_Properties = {
	maxhealth = 210000,
}
So in SP, the hiig MS has a different health than MP.

@Echo1707 - Would you mind documenting all of these from 2.205 here:
https://github.com/HW-PlayersPatch/2.3/wiki/SP-Only-Stats

We need to be aware of this when were changing .ship files for MP/SP.

**Comment by Echo1707** [comment]
I should watch all the new comments before commenting ^^
That's great! I'll take care of it ;)

**Comment by Echo1707** [comment]
I've updated the wiki with 100% of the ships that have a singleplayer file that changes at least one value.

I added a few ships that I know have the strings in .ship to adjust SP values, but that have no SP file (e.g. the Kushan Research Ship).

**Comment by cloaked2222** [comment]
Thanks man!

Proposed changes:
Kus MS maxhealth SP=210000 MP=280000
SP health should just use MP health. Sometimes the enemy just ignores your fleet and goes straight to sinking your MS which can pop fast to a bunch of frigs...

Tai Missile Destroyer CanAttackFams
SP= "Capturer, Corvette, Fighter, Frigate, SmallCapitalShip, BigCapitalShip, Mothership, Utility"
MP= "Fighter, Fighter_hw1, Corvette, Corvette_hw1, Utility,,,,,, Frigate, SmallCapitalShip, BigCapitalShip, Mothership"
SP value is way old and makes no sense. Move corvettes ahead of fighters in the priority for MP, then update SP to match.
Just realized all ships in the game will prioritize attacking hw2 fighters/corvs over hw1... -_- 

Hiig MS maxhealth SP=210000, MP=240000
SP health should just use MP health. Looks like gearbox lowered base health for SP to be closer to hw2c, but since there's no level 2 upgrades, that's not a great idea for the later missions.

Vay Gun Plats
SP maxhealth = 6500
MP maxhealth = 5000
Dunno why it was buffed for SP. Unless anyone's against, propose SP to match MP.

Vay Assault Frigate side/rearArmourDamage
SP=1.0
MP=1.2
Dunno why it was buffed for SP. It wasn't like this in hw2c, so I propose SP should match MP.

Vay DD:
SP maxhealth = 87000
MP maxhealth = 85000
SP already has some over-the-top health for vay capital ships. Not only do they have 2x and 3x health upgrades from hw2c, but gbx also gave them 0.85 sideArmourDamage on most capital ships. Propose SP to match MP.

Vay Cruiser:
SP maxhealth = 200000
MP maxhealth = 192000
Ditto

Vay Flagship:
SP maxhealth = 275000
MP maxhealth = 250000
Ditto

If these changes make sense. Rather than copying MP values to SP, we want to just delete the applicable line here: ship\x\singleplayer\props\default.lua

**Comment by Echo1707** [comment]
> Kus MS maxhealth SP=210000 MP=280000
SP health should just use MP health. Sometimes the enemy just ignores your fleet and goes straight to sinking your MS which can pop fast to a bunch of frigs...

I recall 3 instances in the HW1 campaign where the MS was focused:
- M04: a few Turanic Raiders Ion Array Frigates jump in surrounding the MS; Turanics in general are very easy to deal with, especially with the upcoming heavy corvettes increased DPS vs frigates.
- M08: a lot of Kadeshi Multibeam Frigates walk their way to the MS; this is actually the very first threat of a gameover, but only if the player is catched off-guard, without scouting and with their DDs and ions going after any other Kadeshi MS that isn't the closest one (the one in front and high); this is easily the most rewarding mission in terms of firepower if one salvage the multibeams frigates, so it should come with a price; and again, heavy corvettes are receiving a buff
- M16: this is the last mission, so it's natural that it is the hardest; however the only threat is the very beginning, with the cross of ions coming from below and the frigs and supercapitals coming from the front... lack of resources should have already taught players to keep their units alive and in good shape, in M08 they learned to heal the MS, in missions 12 & M15 they get a hint about Cloak Generators, so in M16 they are supposed to: keep the MS cloaked, tell all repair units to repair the MS, deal with the ion cannons cross with bombers/heavies/salvettes, deal with the frigates and supercapitals with their own frigs (and here is where the Kadeshi Multibeam Frigates come in handy) and supercapitals. Even if one doesn't have the multibeam frigs, they are still given the opportunity to salvage ion frigates on M14.

HW1 is an oldschool game, where people are given hints during the campaign and they are supposed to learn and use them, where you don't have much free room but are supposed to do certain things to succeed. The campaign is already easy in RM, please don't make it any easier.

> Just realized all ships in the game will prioritize attacking hw2 fighters/corvs over hw1... -_-

Not if we give HW1 units a higher target priority for HW1 families ;) For example, HW2 ints focus HW2 ints first and then HW1 ints, while HW1 ints focus first HW1 ints and then HW2 ints, and so on.

> Hiig MS maxhealth SP=210000, MP=240000
SP health should just use MP health. Looks like gearbox lowered base health for SP to be closer to hw2c, but since there's no level 2 upgrades, that's not a great idea for the later missions.

I don't recall any instances in the HW2 campaign where the MS was focused by enemy ships...

Most Vay units: I agree that they feel harder to kill in the campaign, but could we remove the side/rear armour damage before tweaking their healt? Why should a destroyer take more damage from the front than from the sides?

**Comment by cloaked2222** [comment]
MS health can stay the same then.

At first I was thinking remove the vay capital side/rear stuff too, but at-least gearbox gave all vay capital ships (besides CC's) a consistent 15% buff. We could remove this too, but it would be a larger nerf.

The plain health buffs are 2% (DD), 4% (BC), and 10%(FS). These are barely noticeable in the campaign and should prolly come out for MP/SP consistency. The classics did not have separate SP/MP base stats, and generally I'm against this unless there's good reason (like vay cc). Vay cc MP health was buffed in v2.0, so its SP health is purposely lower to balance an early mission.

**Comment by cloaked2222** [comment]
Implemented:
https://github.com/HW-PlayersPatch/2.3/commit/d4c9e17be510901bc13b70dabd6b595b279ba0a4

Closing this issue. Feel free to re-open any issues if more discussion/changes are required.
